
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.xacttime;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Sat Apr 26 12:12:32 MST 2014
 * Generated source version: 2.2.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "Synergy",
                      portName = "SynergySoap",
                      targetNamespace = "http://xacttime.com/",
                      wsdlLocation = "file:/home/chaol/Development/repo/synergy-java-client/synergyapps-parent/synergyapps-webservices/src/main/resources/xacttime_synergy_v2.wsdl",
                      endpointInterface = "com.xacttime.SynergySoap")
                      
public class SynergySoapImpl implements SynergySoap {

    private static final Logger LOG = Logger.getLogger(SynergySoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.xacttime.SynergySoap#getFingerprints(java.lang.String  webServicesKey ,)int  terminalId )*
     */
    public com.xacttime.ArrayOfFingerprint getFingerprints(java.lang.String webServicesKey,int terminalId) { 
        LOG.info("Executing operation getFingerprints");
        System.out.println(webServicesKey);
        System.out.println(terminalId);
        try {
            com.xacttime.ArrayOfFingerprint _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xacttime.SynergySoap#getEmployees(java.lang.String  webServicesKey ,)int  terminalId )*
     */
    public com.xacttime.ArrayOfEmployee getEmployees(java.lang.String webServicesKey,int terminalId) { 
        LOG.info("Executing operation getEmployees");
        System.out.println(webServicesKey);
        System.out.println(terminalId);
        try {
            com.xacttime.ArrayOfEmployee _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xacttime.SynergySoap#getOptions(java.lang.String  webServicesKey ,)int  terminalId )*
     */
    public com.xacttime.Options getOptions(java.lang.String webServicesKey,int terminalId) { 
        LOG.info("Executing operation getOptions");
        System.out.println(webServicesKey);
        System.out.println(terminalId);
        try {
            com.xacttime.Options _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xacttime.SynergySoap#recordPunches(java.lang.String  webServicesKey ,)int  terminalId ,)com.xacttime.ArrayOfPunchData  punches )*
     */
    public com.xacttime.ArrayOfPunchStatus recordPunches(java.lang.String webServicesKey,int terminalId,com.xacttime.ArrayOfPunchData punches) { 
        LOG.info("Executing operation recordPunches");
        System.out.println(webServicesKey);
        System.out.println(terminalId);
        System.out.println(punches);
        try {
            com.xacttime.ArrayOfPunchStatus _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xacttime.SynergySoap#getLaborLevels(java.lang.String  webServicesKey )*
     */
    public com.xacttime.ArrayOfLaborLevel getLaborLevels(java.lang.String webServicesKey) { 
        LOG.info("Executing operation getLaborLevels");
        System.out.println(webServicesKey);
        try {
            com.xacttime.ArrayOfLaborLevel _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xacttime.SynergySoap#recordPunch(java.lang.String  webServicesKey ,)int  terminalId ,)com.xacttime.PunchData  punch )*
     */
    public com.xacttime.PunchStatus recordPunch(java.lang.String webServicesKey,int terminalId,com.xacttime.PunchData punch) { 
        LOG.info("Executing operation recordPunch");
        System.out.println(webServicesKey);
        System.out.println(terminalId);
        System.out.println(punch);
        try {
            com.xacttime.PunchStatus _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xacttime.SynergySoap#setFingerprint(java.lang.String  webServicesKey ,)com.xacttime.Fingerprint  fingerprint )*
     */
    public boolean setFingerprint(java.lang.String webServicesKey,com.xacttime.Fingerprint fingerprint) { 
        LOG.info("Executing operation setFingerprint");
        System.out.println(webServicesKey);
        System.out.println(fingerprint);
        try {
            boolean _return = false;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
