package com.xacttime;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Sat Apr 26 12:12:32 MST 2014
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://xacttime.com/", name = "SynergySoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SynergySoap {

    @WebResult(name = "GetFingerprintsResult", targetNamespace = "http://xacttime.com/")
    @RequestWrapper(localName = "GetFingerprints", targetNamespace = "http://xacttime.com/", className = "com.xacttime.GetFingerprints")
    @ResponseWrapper(localName = "GetFingerprintsResponse", targetNamespace = "http://xacttime.com/", className = "com.xacttime.GetFingerprintsResponse")
    @WebMethod(operationName = "GetFingerprints", action = "http://xacttime.com/GetFingerprints")
    public com.xacttime.ArrayOfFingerprint getFingerprints(
        @WebParam(name = "webServicesKey", targetNamespace = "http://xacttime.com/")
        java.lang.String webServicesKey,
        @WebParam(name = "terminalId", targetNamespace = "http://xacttime.com/")
        int terminalId
    );

    @WebResult(name = "GetEmployeesResult", targetNamespace = "http://xacttime.com/")
    @RequestWrapper(localName = "GetEmployees", targetNamespace = "http://xacttime.com/", className = "com.xacttime.GetEmployees")
    @ResponseWrapper(localName = "GetEmployeesResponse", targetNamespace = "http://xacttime.com/", className = "com.xacttime.GetEmployeesResponse")
    @WebMethod(operationName = "GetEmployees", action = "http://xacttime.com/GetEmployees")
    public com.xacttime.ArrayOfEmployee getEmployees(
        @WebParam(name = "webServicesKey", targetNamespace = "http://xacttime.com/")
        java.lang.String webServicesKey,
        @WebParam(name = "terminalId", targetNamespace = "http://xacttime.com/")
        int terminalId
    );

    @WebResult(name = "GetOptionsResult", targetNamespace = "http://xacttime.com/")
    @RequestWrapper(localName = "GetOptions", targetNamespace = "http://xacttime.com/", className = "com.xacttime.GetOptions")
    @ResponseWrapper(localName = "GetOptionsResponse", targetNamespace = "http://xacttime.com/", className = "com.xacttime.GetOptionsResponse")
    @WebMethod(operationName = "GetOptions", action = "http://xacttime.com/GetOptions")
    public com.xacttime.Options getOptions(
        @WebParam(name = "webServicesKey", targetNamespace = "http://xacttime.com/")
        java.lang.String webServicesKey,
        @WebParam(name = "terminalId", targetNamespace = "http://xacttime.com/")
        int terminalId
    );

    @WebResult(name = "RecordPunchesResult", targetNamespace = "http://xacttime.com/")
    @RequestWrapper(localName = "RecordPunches", targetNamespace = "http://xacttime.com/", className = "com.xacttime.RecordPunches")
    @ResponseWrapper(localName = "RecordPunchesResponse", targetNamespace = "http://xacttime.com/", className = "com.xacttime.RecordPunchesResponse")
    @WebMethod(operationName = "RecordPunches", action = "http://xacttime.com/RecordPunches")
    public com.xacttime.ArrayOfPunchStatus recordPunches(
        @WebParam(name = "webServicesKey", targetNamespace = "http://xacttime.com/")
        java.lang.String webServicesKey,
        @WebParam(name = "terminalId", targetNamespace = "http://xacttime.com/")
        int terminalId,
        @WebParam(name = "punches", targetNamespace = "http://xacttime.com/")
        com.xacttime.ArrayOfPunchData punches
    );

    @WebResult(name = "GetLaborLevelsResult", targetNamespace = "http://xacttime.com/")
    @RequestWrapper(localName = "GetLaborLevels", targetNamespace = "http://xacttime.com/", className = "com.xacttime.GetLaborLevels")
    @ResponseWrapper(localName = "GetLaborLevelsResponse", targetNamespace = "http://xacttime.com/", className = "com.xacttime.GetLaborLevelsResponse")
    @WebMethod(operationName = "GetLaborLevels", action = "http://xacttime.com/GetLaborLevels")
    public com.xacttime.ArrayOfLaborLevel getLaborLevels(
        @WebParam(name = "webServicesKey", targetNamespace = "http://xacttime.com/")
        java.lang.String webServicesKey
    );

    @WebResult(name = "RecordPunchResult", targetNamespace = "http://xacttime.com/")
    @RequestWrapper(localName = "RecordPunch", targetNamespace = "http://xacttime.com/", className = "com.xacttime.RecordPunch")
    @ResponseWrapper(localName = "RecordPunchResponse", targetNamespace = "http://xacttime.com/", className = "com.xacttime.RecordPunchResponse")
    @WebMethod(operationName = "RecordPunch", action = "http://xacttime.com/RecordPunch")
    public com.xacttime.PunchStatus recordPunch(
        @WebParam(name = "webServicesKey", targetNamespace = "http://xacttime.com/")
        java.lang.String webServicesKey,
        @WebParam(name = "terminalId", targetNamespace = "http://xacttime.com/")
        int terminalId,
        @WebParam(name = "punch", targetNamespace = "http://xacttime.com/")
        com.xacttime.PunchData punch
    );

    @WebResult(name = "SetFingerprintResult", targetNamespace = "http://xacttime.com/")
    @RequestWrapper(localName = "SetFingerprint", targetNamespace = "http://xacttime.com/", className = "com.xacttime.SetFingerprint")
    @ResponseWrapper(localName = "SetFingerprintResponse", targetNamespace = "http://xacttime.com/", className = "com.xacttime.SetFingerprintResponse")
    @WebMethod(operationName = "SetFingerprint", action = "http://xacttime.com/SetFingerprint")
    public boolean setFingerprint(
        @WebParam(name = "webServicesKey", targetNamespace = "http://xacttime.com/")
        java.lang.String webServicesKey,
        @WebParam(name = "fingerprint", targetNamespace = "http://xacttime.com/")
        com.xacttime.Fingerprint fingerprint
    );
}
