
/*
 * 
 */

package com.xacttime;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Sat Apr 26 12:12:32 MST 2014
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "Synergy", 
                  wsdlLocation = "file:/home/chaol/Development/repo/synergy-java-client/synergyapps-parent/synergyapps-webservices/src/main/resources/xacttime_synergy_v2.wsdl",
                  targetNamespace = "http://xacttime.com/") 
public class Synergy extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://xacttime.com/", "Synergy");
    public final static QName SynergySoap = new QName("http://xacttime.com/", "SynergySoap");
    public final static QName SynergySoap12 = new QName("http://xacttime.com/", "SynergySoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/chaol/Development/repo/synergy-java-client/synergyapps-parent/synergyapps-webservices/src/main/resources/xacttime_synergy_v2.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/home/chaol/Development/repo/synergy-java-client/synergyapps-parent/synergyapps-webservices/src/main/resources/xacttime_synergy_v2.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public Synergy(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Synergy(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Synergy() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SynergySoap
     */
    @WebEndpoint(name = "SynergySoap")
    public SynergySoap getSynergySoap() {
        return super.getPort(SynergySoap, SynergySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SynergySoap
     */
    @WebEndpoint(name = "SynergySoap")
    public SynergySoap getSynergySoap(WebServiceFeature... features) {
        return super.getPort(SynergySoap, SynergySoap.class, features);
    }
    /**
     * 
     * @return
     *     returns SynergySoap
     */
    @WebEndpoint(name = "SynergySoap12")
    public SynergySoap getSynergySoap12() {
        return super.getPort(SynergySoap12, SynergySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SynergySoap
     */
    @WebEndpoint(name = "SynergySoap12")
    public SynergySoap getSynergySoap12(WebServiceFeature... features) {
        return super.getPort(SynergySoap12, SynergySoap.class, features);
    }

}
