
package com.xacttime;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Synergy", targetNamespace = "http://xacttime.com/", wsdlLocation = "http://dev6511/XactTime/webservices/v2/synergy.asmx?WSDL")
public class Synergy
    extends Service
{

    private final static URL SYNERGY_WSDL_LOCATION;
    private final static WebServiceException SYNERGY_EXCEPTION;
    private final static QName SYNERGY_QNAME = new QName("http://xacttime.com/", "Synergy");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dev6511/XactTime/webservices/v2/synergy.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SYNERGY_WSDL_LOCATION = url;
        SYNERGY_EXCEPTION = e;
    }

    public Synergy() {
        super(__getWsdlLocation(), SYNERGY_QNAME);
    }

    public Synergy(WebServiceFeature... features) {
        super(__getWsdlLocation(), SYNERGY_QNAME, features);
    }

    public Synergy(URL wsdlLocation) {
        super(wsdlLocation, SYNERGY_QNAME);
    }

    public Synergy(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SYNERGY_QNAME, features);
    }

    public Synergy(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Synergy(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SynergySoap
     */
    @WebEndpoint(name = "SynergySoap")
    public SynergySoap getSynergySoap() {
        return super.getPort(new QName("http://xacttime.com/", "SynergySoap"), SynergySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SynergySoap
     */
    @WebEndpoint(name = "SynergySoap")
    public SynergySoap getSynergySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://xacttime.com/", "SynergySoap"), SynergySoap.class, features);
    }

    /**
     * 
     * @return
     *     returns SynergySoap
     */
    @WebEndpoint(name = "SynergySoap12")
    public SynergySoap getSynergySoap12() {
        return super.getPort(new QName("http://xacttime.com/", "SynergySoap12"), SynergySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SynergySoap
     */
    @WebEndpoint(name = "SynergySoap12")
    public SynergySoap getSynergySoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://xacttime.com/", "SynergySoap12"), SynergySoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SYNERGY_EXCEPTION!= null) {
            throw SYNERGY_EXCEPTION;
        }
        return SYNERGY_WSDL_LOCATION;
    }

}
