
package com.xacttime;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SynergySoap", targetNamespace = "http://xacttime.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SynergySoap {


    /**
     * 
     * @param terminalId
     * @param punch
     * @param webServicesKey
     * @return
     *     returns com.xacttime.PunchStatus
     */
    @WebMethod(operationName = "RecordPunch", action = "http://xacttime.com/RecordPunch")
    @WebResult(name = "RecordPunchResult", targetNamespace = "http://xacttime.com/")
    @RequestWrapper(localName = "RecordPunch", targetNamespace = "http://xacttime.com/", className = "com.xacttime.RecordPunch")
    @ResponseWrapper(localName = "RecordPunchResponse", targetNamespace = "http://xacttime.com/", className = "com.xacttime.RecordPunchResponse")
    public PunchStatus recordPunch(
        @WebParam(name = "webServicesKey", targetNamespace = "http://xacttime.com/")
        String webServicesKey,
        @WebParam(name = "terminalId", targetNamespace = "http://xacttime.com/")
        int terminalId,
        @WebParam(name = "punch", targetNamespace = "http://xacttime.com/")
        PunchData punch);

    /**
     * 
     * @param terminalId
     * @param webServicesKey
     * @param punches
     * @return
     *     returns com.xacttime.ArrayOfPunchStatus
     */
    @WebMethod(operationName = "RecordPunches", action = "http://xacttime.com/RecordPunches")
    @WebResult(name = "RecordPunchesResult", targetNamespace = "http://xacttime.com/")
    @RequestWrapper(localName = "RecordPunches", targetNamespace = "http://xacttime.com/", className = "com.xacttime.RecordPunches")
    @ResponseWrapper(localName = "RecordPunchesResponse", targetNamespace = "http://xacttime.com/", className = "com.xacttime.RecordPunchesResponse")
    public ArrayOfPunchStatus recordPunches(
        @WebParam(name = "webServicesKey", targetNamespace = "http://xacttime.com/")
        String webServicesKey,
        @WebParam(name = "terminalId", targetNamespace = "http://xacttime.com/")
        int terminalId,
        @WebParam(name = "punches", targetNamespace = "http://xacttime.com/")
        ArrayOfPunchData punches);

    /**
     * 
     * @param terminalId
     * @param webServicesKey
     * @return
     *     returns com.xacttime.ArrayOfEmployee
     */
    @WebMethod(operationName = "GetEmployees", action = "http://xacttime.com/GetEmployees")
    @WebResult(name = "GetEmployeesResult", targetNamespace = "http://xacttime.com/")
    @RequestWrapper(localName = "GetEmployees", targetNamespace = "http://xacttime.com/", className = "com.xacttime.GetEmployees")
    @ResponseWrapper(localName = "GetEmployeesResponse", targetNamespace = "http://xacttime.com/", className = "com.xacttime.GetEmployeesResponse")
    public ArrayOfEmployee getEmployees(
        @WebParam(name = "webServicesKey", targetNamespace = "http://xacttime.com/")
        String webServicesKey,
        @WebParam(name = "terminalId", targetNamespace = "http://xacttime.com/")
        int terminalId);

    /**
     * 
     * @param webServicesKey
     * @return
     *     returns com.xacttime.ArrayOfLaborLevel
     */
    @WebMethod(operationName = "GetLaborLevels", action = "http://xacttime.com/GetLaborLevels")
    @WebResult(name = "GetLaborLevelsResult", targetNamespace = "http://xacttime.com/")
    @RequestWrapper(localName = "GetLaborLevels", targetNamespace = "http://xacttime.com/", className = "com.xacttime.GetLaborLevels")
    @ResponseWrapper(localName = "GetLaborLevelsResponse", targetNamespace = "http://xacttime.com/", className = "com.xacttime.GetLaborLevelsResponse")
    public ArrayOfLaborLevel getLaborLevels(
        @WebParam(name = "webServicesKey", targetNamespace = "http://xacttime.com/")
        String webServicesKey);

    /**
     * 
     * @param terminalId
     * @param webServicesKey
     * @return
     *     returns com.xacttime.Options
     */
    @WebMethod(operationName = "GetOptions", action = "http://xacttime.com/GetOptions")
    @WebResult(name = "GetOptionsResult", targetNamespace = "http://xacttime.com/")
    @RequestWrapper(localName = "GetOptions", targetNamespace = "http://xacttime.com/", className = "com.xacttime.GetOptions")
    @ResponseWrapper(localName = "GetOptionsResponse", targetNamespace = "http://xacttime.com/", className = "com.xacttime.GetOptionsResponse")
    public Options getOptions(
        @WebParam(name = "webServicesKey", targetNamespace = "http://xacttime.com/")
        String webServicesKey,
        @WebParam(name = "terminalId", targetNamespace = "http://xacttime.com/")
        int terminalId);

    /**
     * 
     * @param terminalId
     * @param webServicesKey
     * @return
     *     returns com.xacttime.ArrayOfFingerprint
     */
    @WebMethod(operationName = "GetFingerprints", action = "http://xacttime.com/GetFingerprints")
    @WebResult(name = "GetFingerprintsResult", targetNamespace = "http://xacttime.com/")
    @RequestWrapper(localName = "GetFingerprints", targetNamespace = "http://xacttime.com/", className = "com.xacttime.GetFingerprints")
    @ResponseWrapper(localName = "GetFingerprintsResponse", targetNamespace = "http://xacttime.com/", className = "com.xacttime.GetFingerprintsResponse")
    public ArrayOfFingerprint getFingerprints(
        @WebParam(name = "webServicesKey", targetNamespace = "http://xacttime.com/")
        String webServicesKey,
        @WebParam(name = "terminalId", targetNamespace = "http://xacttime.com/")
        int terminalId);

    /**
     * 
     * @param fingerprint
     * @param webServicesKey
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetFingerprint", action = "http://xacttime.com/SetFingerprint")
    @WebResult(name = "SetFingerprintResult", targetNamespace = "http://xacttime.com/")
    @RequestWrapper(localName = "SetFingerprint", targetNamespace = "http://xacttime.com/", className = "com.xacttime.SetFingerprint")
    @ResponseWrapper(localName = "SetFingerprintResponse", targetNamespace = "http://xacttime.com/", className = "com.xacttime.SetFingerprintResponse")
    public boolean setFingerprint(
        @WebParam(name = "webServicesKey", targetNamespace = "http://xacttime.com/")
        String webServicesKey,
        @WebParam(name = "fingerprint", targetNamespace = "http://xacttime.com/")
        Fingerprint fingerprint);

}
