package com.synel.synergy.synergy2416.persistent;

public class TransactionDataPOJO {
	
	/**
	 * 
	 */
	public long id; //auto generated by db
	private long timestamp; //milliseconds after epoch
	private boolean uploaded=false;
	private PunchDataPOJO pd;
	/**
	 * @return the id
	 */
	public long getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(long id) {
		this.id = id;
	}
	/**
	 * @return the uploaded
	 */
	public boolean isUploaded() {
		return uploaded;
	}
	/**
	 * @param uploaded the uploaded to set
	 */
	public void setUploaded(boolean uploaded) {
		this.uploaded = uploaded;
	}
	/**
	 * @return the pd
	 */
	public PunchDataPOJO getPd() {
		return pd;
	}
	/**
	 * @param pd the pd to set
	 */
	public void setPd(PunchDataPOJO pd) {
		this.pd = pd;
	}
	/**
	 * @return the timestamp
	 */
	public long getTimestamp() {
		return timestamp;
	}
	/**
	 * @param timestamp the timestamp to set
	 */
	public void setTimestamp(long timestamp) {
		this.timestamp = timestamp;
	}
	
	@Override
	public String toString(){
		String res = "ID: "+id+" TimeStamp: "+timestamp+" Uploaded "+uploaded + "\n";
		return res+" PunchData: "+pd.toString();
	}

}