package com.synel.synergy.synergy2416.persistent;

import com.xacttime.PunchData;

public class TransactionData {
	
	/**
	 * 
	 */
	public long id; //auto generated by db
	protected long timestamp; //milliseconds after epoch
	protected boolean uploaded=false;
	protected PunchData pd;
	/**
	 * @return the id
	 */
	public long getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(long id) {
		this.id = id;
	}
	/**
	 * @return the uploaded
	 */
	public boolean isUploaded() {
		return uploaded;
	}
	/**
	 * @param uploaded the uploaded to set
	 */
	public void setUploaded(boolean uploaded) {
		this.uploaded = uploaded;
	}
	/**
	 * @return the pd
	 */
	public PunchData getPd() {
		return pd;
	}
	/**
	 * @param pd the pd to set
	 */
	public void setPd(PunchData pd) {
		this.pd = pd;
	}
	/**
	 * @return the timestamp
	 */
	public long getTimestamp() {
		return timestamp;
	}
	/**
	 * @param timestamp the timestamp to set
	 */
	public void setTimestamp(long timestamp) {
		this.timestamp = timestamp;
	}

}